[package]
name = "proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-config = "1.8.0"
aws-sdk-lambda = "1.84.0"
lambda_runtime = "0.14.2"
serde = "1.0.219"
serde_json = "1.0.140"
tokio = "1.45.1"

[[bin]]
name = "proxy"
path = "src/main.rs"
