version = 0.1
[default.global.parameters]
stack_name = "perftest"

[default.build.parameters]
beta_features = true

[default.deploy.parameters]
resolve_s3 = true
s3_prefix = "perftest"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
