name: "Continuous Build (Makefile & Scripts)"

on:
  push:
    paths:
      - 'Makefile'
      - '**/*.sh'
      - '.github/workflows/ci-makefile.yml'
    branches:
      - main
  pull_request:
    paths:
      - 'Makefile'
      - '**/*.sh'
      - '.github/workflows/ci-makefile.yml'
    branches:
      - main

permissions:
  contents: read

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install shell check
        run: sudo apt update && sudo apt install --assume-yes shellcheck

      - name: Run shellcheck
        run: >-
          find . -type f |
          grep -v '.git' |
          xargs -n 30 file |
          grep -i shell |
          awk -F':' '{print $1}' |
          xargs shellcheck

  makefile-syntax:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check Makefile syntax
        run: |
          make --dry-run help
          echo "✅ Makefile syntax is valid"

  makefile-targets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Test Makefile help target
        run: |
          make help
          echo "✅ Makefile help target works"

      - name: Test clean targets (dry-run)
        run: |
          make --dry-run clean-dist
          make --dry-run clean-clone
          echo "✅ Clean targets are valid" 